// lib/utils/slug.ts
//
// Slug utilities.
//
// IMPORTANT: NFC card slugs are generated by the database function generate_unique_slug()
// defined in DATABASE.md. The 6-character alphanumeric slug is created on INSERT into
// nfc_cards and NEVER changes.
//
// This file provides:
//   - Client-side slug validation (for admin forms)
//   - Company slug generation (for companies.slug, which IS editable — different from nfc slugs)

const NFC_SLUG_CHARS = 'abcdefghjkmnpqrstuvwxyz23456789'
const NFC_SLUG_LENGTH = 6

/**
 * Validate that a string looks like a valid NFC card slug.
 * Slugs are 6 characters, lowercase alphanumeric, no ambiguous chars (0, O, 1, l, i).
 */
export function isValidNfcSlug(slug: string): boolean {
  if (slug.length !== NFC_SLUG_LENGTH) return false
  return slug.split('').every((c) => NFC_SLUG_CHARS.includes(c))
}

/**
 * Generate a URL-safe company slug from a company name.
 * Used for companies.slug (e.g. "Karam Africa" → "karam-africa").
 *
 * NOTE: This is the company's URL identifier, NOT the NFC card slug.
 *       NFC slugs are generated by the database — never generate them here.
 */
export function generateCompanySlug(name: string): string {
  return name
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9\s-]/g, '') // strip special chars
    .replace(/\s+/g, '-')         // spaces → hyphens
    .replace(/-+/g, '-')          // collapse multiple hyphens
    .replace(/^-|-$/g, '')        // trim leading/trailing hyphens
}
